# Generated by Django 5.2 on 2025-05-02 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissionaryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=100)),
                ('date_taken', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='missionary_photos/')),
                ('category', models.CharField(default='South Sudan', max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Missionary Photo',
                'verbose_name_plural': 'Missionary Photos',
                'ordering': ['-date_taken'],
            },
        ),
    ]
