# Generated by Django 5.1.7 on 2025-05-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionary_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionaryphoto',
            name='card_position',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Card 1 - Gospel Outreach'), (2, 'Card 2 - Church Building'), (3, 'Card 3 - Community Support')], help_text='Assign a specific card position (1-3) for homepage display.', null=True),
        ),
    ]
